# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: python leap.py
  displayName: 'Run a one-line script'

- script: python hello.py
  displayName: 'Run a two-line script'
  
- script: python add.py
  displayName: 'Run a multi-line script'
